---
all:
  vars:
    ansible_user: automation
  children:
    k3s_cluster:
      children:
        k3s_control_plane:
          hosts:
            control-1:
              ansible_host: 10.10.30.11
            control-2:
              ansible_host: 10.10.30.12
            control-3:
              ansible_host: 10.10.30.13
        k3s_workers:
          hosts:
            worker-1:
              ansible_host: 10.10.30.21
            worker-2:
              ansible_host: 10.10.30.22
